name: Test dispatch med debug

on:
  workflow_dispatch:

jobs:
  dispatch-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Visa PAT-längd (för debug, visa aldrig token i klartext!)
        run: echo "PAT length ${{ secrets.PAT && secrets.PAT.length || 'undefined' }}"

      - name: Kör dispatch-script med debug
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          echo "Kör dispatch med version 1.0.0"
          node -e "
            import https from 'https';
            import { env, stdout } from 'process';

            const version = '1.0.0';
            if (!env.PAT) {
              console.error('PAT saknas!');
              process.exit(1);
            }

            const data = JSON.stringify({
              event_type: 'npm-package-updated',
              client_payload: { version }
            });

            const options = {
              hostname: 'api.github.com',
              path: '/repos/maxwelin/frk-24s-J-frontend/dispatches',
              method: 'POST',
              headers: {
                Authorization: \`Bearer \${env.PAT}\`,
                'User-Agent': 'debug-script',
                Accept: 'application/vnd.github+json',
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(data)
              }
            };

            const req = https.request(options, res => {
              console.log(\`Statuscode: \${res.statusCode}\`);
              let responseData = '';
              res.on('data', d => responseData += d);
              res.on('end', () => {
                if (responseData) console.log('Svar från API:', responseData);
              });
            });

            req.on('error', error => {
              console.error('Fel vid dispatch:', error);
            });

            req.write(data);
            req.end();
          "
